"""
extraction.py
-------------
Extract counts from source and background regions in NuSTAR event files.

Regions are defined as circles in sky (RA/Dec) coordinates. Events are
filtered by their X,Y pixel positions using the WCS transformation.

Energy filtering supports named bands, custom keV ranges, and direct PI ranges.

NuSTAR PI channel formula
--------------------------
  E(keV) = 0.04 × PI + 1.6
  PI = (E_keV − 1.6) / 0.04

Verified against NuSTAR CALDB (epoch ~2023):
  3  keV  →  PI =  35
  10 keV  →  PI = 210
  30 keV  →  PI = 710
  79 keV  →  PI = 1935

Note: The gain (0.04 keV/ch) and offset (1.6 keV) are stable to ~1% across
the mission lifetime and detector temperatures. For precision spectroscopy
use the CALDB RMF, but for count extraction this formula is accurate.
"""

import numpy as np
from astropy.wcs import WCS


# ── Named energy bands ────────────────────────────────────────────────────
# Each entry: (pi_min, pi_max, e_lo_kev, e_hi_kev, label)
ENERGY_BANDS = {
    "full":      (  35, 1935,  3.0, 79.0, "3–79 keV"),
    "soft":      (  35,  210,  3.0, 10.0, "3–10 keV"),
    "hard":      ( 210,  710, 10.0, 30.0, "10–30 keV"),
    "ultrahard": ( 710, 1935, 30.0, 79.0, "30–79 keV"),
}

# Compact display name used in plots and CLI help
BAND_DISPLAY = {k: f"{k}  ({v[4]})" for k, v in ENERGY_BANDS.items()}


def energy_to_pi(e_kev):
    """
    Convert energy in keV to NuSTAR PI channel (integer, inclusive lower bound).

    Formula: PI = (E_keV − 1.6) / 0.04
    This matches the NuSTAR CALDB gain/offset for the FPM detectors.
    """
    pi = (e_kev - 1.6) / 0.04
    return max(0, int(round(pi)))


def pi_to_energy(pi):
    """Convert NuSTAR PI channel to energy in keV. E = 0.04×PI + 1.6"""
    return 0.04 * pi + 1.6


def parse_band(band_spec):
    """
    Parse a band specification into (pi_min, pi_max, e_lo, e_hi, label).

    Accepted formats
    ----------------
    Named band  : 'soft', 'hard', 'full', 'ultrahard'
    keV range   : '8-30', '8:30', '8,30'   (lo-hi in keV, float)
    PI range    : 'pi:300:700'              (explicit PI channels)

    Returns
    -------
    (pi_min, pi_max, e_lo_kev, e_hi_kev, display_label) : tuple
    """
    spec = str(band_spec).strip().lower()

    # Named band
    if spec in ENERGY_BANDS:
        return ENERGY_BANDS[spec]

    # PI explicit: 'pi:300:700'
    if spec.startswith("pi"):
        parts = spec.replace("pi", "").strip(":/,").split(":")
        if len(parts) == 2:
            pi_lo, pi_hi = int(parts[0]), int(parts[1])
            e_lo = round(pi_to_energy(pi_lo), 2)
            e_hi = round(pi_to_energy(pi_hi), 2)
            return (pi_lo, pi_hi, e_lo, e_hi, f"{e_lo}–{e_hi} keV (custom)")

    # keV range with separator: '8-30', '8:30', '8,30', '8 30'
    for sep in ("-", ":", ",", " "):
        if sep in spec:
            parts = spec.split(sep, 1)
            try:
                e_lo = float(parts[0])
                e_hi = float(parts[1])
                pi_lo = energy_to_pi(e_lo)
                pi_hi = energy_to_pi(e_hi)
                return (pi_lo, pi_hi, e_lo, e_hi, f"{e_lo}–{e_hi} keV (custom)")
            except (ValueError, IndexError):
                continue

    raise ValueError(
        f"Cannot parse band specification '{band_spec}'.\n"
        f"  Named bands: {list(ENERGY_BANDS.keys())}\n"
        f"  Custom keV range examples: '8-30', '8:30', '15,50'\n"
        f"  Custom PI range example:   'pi:300:700'"
    )


def filter_events_energy(events, band="soft"):
    """
    Return boolean mask for events within an energy band.

    Parameters
    ----------
    events : numpy recarray — events table from FITS
    band   : str | tuple
             Named band key, custom keV string ('8-30'), or
             raw (pi_min, pi_max) tuple.

    Returns
    -------
    mask : boolean array
    """
    if isinstance(band, tuple):
        # Raw (pi_min, pi_max) passed directly
        pi_min, pi_max = band[0], band[1]
    else:
        pi_min, pi_max = parse_band(band)[:2]

    pi = events["PI"]
    return (pi >= pi_min) & (pi < pi_max)


# ── Region masks ──────────────────────────────────────────────────────────

def circle_mask(x, y, cx, cy, r):
    """Boolean mask: events inside a circle of radius r centred at (cx,cy)."""
    return (x - cx)**2 + (y - cy)**2 <= r**2


def annulus_mask(x, y, cx, cy, r_in, r_out):
    """Boolean mask: events inside an annulus."""
    d2 = (x - cx)**2 + (y - cy)**2
    return (d2 >= r_in**2) & (d2 <= r_out**2)


# ── Exposure map weighting (optional) ────────────────────────────────────

def load_exposure_map(event_cl_dir, obsid, module, mode="01"):
    """
    Load the NuSTAR exposure map if available (generated by nuexpomap).

    The exposure map corrects for vignetting: pixels at larger off-axis
    angles have lower effective exposure. Weighting counts by the inverse
    of the local exposure normalises out the vignetting effect.

    File name convention: nu{obsid}{module}{mode}_ex.img.gz
    This file is NOT produced on download; it requires running nuexpomap
    from HEASoft. If not found, returns None and analysis proceeds without
    vignetting correction (which is acceptable for small off-axis angles).

    Returns
    -------
    exp_map : 2-D numpy array, or None if file not found
    wcs     : astropy.wcs.WCS, or None
    """
    import glob, os
    from astropy.io import fits
    from astropy.wcs import WCS as AWCS

    pattern = os.path.join(event_cl_dir, f"nu{obsid}{module}{mode}_ex.img.gz")
    matches = glob.glob(pattern)
    if not matches:
        return None, None

    path = matches[0]
    print(f"  Loading exposure map: {os.path.basename(path)}")
    with fits.open(path, memmap=False) as hdul:
        for ext in hdul:
            if ext.data is not None and ext.data.ndim == 2:
                return ext.data.astype(float), AWCS(ext.header, naxis=2)
    return None, None


def effective_exposure_in_region(exp_map, mask_2d):
    """
    Compute the mean effective exposure within a pixel mask.

    Parameters
    ----------
    exp_map  : 2-D array — exposure map (seconds per pixel)
    mask_2d  : 2-D boolean array — same shape as exp_map

    Returns
    -------
    mean_exp : float — mean exposure [s] for pixels in the region
               (use this to vignetting-correct count rates)
    """
    vals = exp_map[mask_2d]
    if len(vals) == 0 or np.all(vals == 0):
        return None
    return float(np.mean(vals[vals > 0]))


# ── Main extraction ───────────────────────────────────────────────────────

def extract_counts(events, events_wcs,
                   src_ra, src_dec, src_radius_pix,
                   bkg_ra, bkg_dec, bkg_radius_pix,
                   bkg_type="circle",
                   bkg_inner_pix=None,
                   energy_band="soft",
                   exp_map=None,
                   exp_wcs=None):
    """
    Extract source and background counts from a NuSTAR event list.

    Parameters
    ----------
    events            : numpy recarray
    events_wcs        : astropy.wcs.WCS
    src_ra/dec        : float  — source RA/Dec in degrees
    src_radius_pix    : float  — source circle radius in pixels
    bkg_ra/dec        : float  — background region centre in degrees
    bkg_radius_pix    : float  — background outer radius in pixels
    bkg_type          : 'circle' or 'annulus'
    bkg_inner_pix     : float  — annulus inner radius (pixels)
    energy_band       : str or (pi_min, pi_max) tuple
    exp_map           : 2-D array or None  — vignetting exposure map
    exp_wcs           : WCS or None

    Returns
    -------
    result : dict
    """
    # Parse band
    band_tuple = parse_band(energy_band) if isinstance(energy_band, str) else energy_band
    pi_min, pi_max, e_lo, e_hi, band_label = band_tuple

    # Energy filter
    e_mask = filter_events_energy(events, (pi_min, pi_max))
    ev = events[e_mask]

    x = ev["X"].astype(float)
    y = ev["Y"].astype(float)

    # Source and background pixel centres
    src_pix = events_wcs.all_world2pix([[src_ra, src_dec]], 0)[0]
    src_cx, src_cy = float(src_pix[0]), float(src_pix[1])

    bkg_pix = events_wcs.all_world2pix([[bkg_ra, bkg_dec]], 0)[0]
    bkg_cx, bkg_cy = float(bkg_pix[0]), float(bkg_pix[1])

    # Source mask
    src_mask = circle_mask(x, y, src_cx, src_cy, src_radius_pix)
    src_counts = int(np.sum(src_mask))

    # Background mask
    if bkg_type == "annulus":
        if bkg_inner_pix is None:
            bkg_inner_pix = src_radius_pix
        bkg_mask = annulus_mask(x, y, bkg_cx, bkg_cy, bkg_inner_pix, bkg_radius_pix)
        bkg_area  = np.pi * (bkg_radius_pix**2 - bkg_inner_pix**2)
    else:
        bkg_mask = circle_mask(x, y, bkg_cx, bkg_cy, bkg_radius_pix)
        bkg_area  = np.pi * bkg_radius_pix**2

    bkg_counts = int(np.sum(bkg_mask))
    src_area   = np.pi * src_radius_pix**2
    alpha      = src_area / bkg_area if bkg_area > 0 else 1.0

    expected_bkg = alpha * bkg_counts
    net_counts   = src_counts - expected_bkg

    # ── Optional exposure-map vignetting correction ───────────────────
    # The exposure map has the same pixel grid as the sky image.
    # We build 2-D masks at integer pixel positions to sample the map.
    vign_src_exp = vign_bkg_exp = vign_factor = None

    if exp_map is not None:
        h, w = exp_map.shape
        ys_g, xs_g = np.mgrid[0:h, 0:w]
        xs_f = xs_g.astype(float)
        ys_f = ys_g.astype(float)

        # Use events_wcs pixel coords (same grid as exposure map if same WCS)
        src_mask_2d = circle_mask(xs_f, ys_f, src_cx, src_cy, src_radius_pix)
        bkg_mask_2d = (
            annulus_mask(xs_f, ys_f, bkg_cx, bkg_cy, bkg_inner_pix or src_radius_pix, bkg_radius_pix)
            if bkg_type == "annulus"
            else circle_mask(xs_f, ys_f, bkg_cx, bkg_cy, bkg_radius_pix)
        )

        vign_src_exp = effective_exposure_in_region(exp_map, src_mask_2d)
        vign_bkg_exp = effective_exposure_in_region(exp_map, bkg_mask_2d)

        if vign_src_exp and vign_bkg_exp and vign_bkg_exp > 0:
            # Vignetting-corrected scaling: weight by local exposure
            vign_factor = vign_src_exp / vign_bkg_exp
            print(f"  Exposure map: src={vign_src_exp:.0f}s  bkg={vign_bkg_exp:.0f}s  "
                  f"vign_factor={vign_factor:.4f}  (vs area ratio α={alpha:.4f})")

    return {
        "src_counts":     src_counts,
        "bkg_counts":     bkg_counts,
        "alpha":          alpha,
        "expected_bkg":   expected_bkg,
        "net_counts":     net_counts,
        "src_cx":         src_cx,
        "src_cy":         src_cy,
        "bkg_cx":         bkg_cx,
        "bkg_cy":         bkg_cy,
        "src_radius_pix": src_radius_pix,
        "bkg_radius_pix": bkg_radius_pix,
        "bkg_inner_pix":  bkg_inner_pix,
        "bkg_type":       bkg_type,
        "src_area":       src_area,
        "bkg_area":       bkg_area,
        "src_mask":       src_mask,
        "bkg_mask":       bkg_mask,
        "n_events_total": len(ev),
        "energy_band":    energy_band,
        "band_label":     band_label,
        "e_lo_kev":       e_lo,
        "e_hi_kev":       e_hi,
        "pi_min":         pi_min,
        "pi_max":         pi_max,
        "vign_src_exp":   vign_src_exp,
        "vign_bkg_exp":   vign_bkg_exp,
        "vign_factor":    vign_factor,
        "ev_x":           x,
        "ev_y":           y,
    }
